name: Deploy assets/readme to WordPress.org
on:
    push:
        branches:
            - main
jobs:
    trunk:
        name: Push to trunk
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: WordPress.org plugin asset/readme update
                uses: 10up/action-wordpress-plugin-asset-update@2.2.0
                env:
                    SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
                    SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
                    SLUG: altinator
                    IGNORE_OTHER_FILES: true
